const VISITOR_ID_COOKIE_MAX_AGE_SECONDS = 365 * 24 * 60 * 60;
const DASHBOARD_MOST_VIEWED_LIMIT = 20;
const VIEW_EVENT_RETENTION_DAYS = 30;
const DASHBOARD_TREND_WINDOW_DAYS = { last7: 7, last30: 30 } as const;

export {
	DASHBOARD_MOST_VIEWED_LIMIT,
	DASHBOARD_TREND_WINDOW_DAYS,
	VIEW_EVENT_RETENTION_DAYS,
	VISITOR_ID_COOKIE_MAX_AGE_SECONDS,
};
