services:
  app:
    build:
      context: .
      target: dev
    hostname: app
    environment:
      DATABASE_URL: "postgres://postgres:postgres@postgres:5432/postgres"
    expose:
      - "3000"
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres
    command: postgres -c 'max_connections=450'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 20
      start_period: 10s

  cache:
    image: redis
    volumes:
      - ./data/redis:/data
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
      interval: 5s
      timeout: 5s
      retries: 20
      start_period: 10s

  nginx:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app
    ports:
      - "4000:80"
