name: test
services:
  app:
    build:
      context: .
      target: test
    hostname: app
    environment:
      DATABASE_URL: "postgres://postgres:postgres@postgres:5432/postgres"
      REDIS_URL: "redis://cache:6379/0"
    expose:
      - "3000"
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres
    command: postgres -c 'max_connections=450'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - type: tmpfs
        target: /var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 20
      start_period: 10s

  cache:
    image: redis
    volumes:
      - ./data/redis:/data
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 20
      start_period: 10s
