enum AuthErrorCode {
  MISSING_TOKEN = "MISSING_TOKEN",
  INVALID_TOKEN = "INVALID_TOKEN",
  SESSION_EXPIRED = "SESSION_EXPIRED",
  USER_NOT_FOUD = "USER_NOT_FOUND",
  SESSION_CREATE_ERROR = "SESSION_CREATE_ERROR",
  SESSION_UPDATE_ERROR = "SESSION_UPDATE_ERROR",
  INVALID_CREDENTIALS = "INVALID_CREDENTIALS",
}

export { AuthErrorCode };
