enum AuthErrorCode {
  MISSING_TOKEN = "MISSING_TOKEN",
  INVALID_TOKEN = "INVALID_TOKEN",
  SESSION_EXPIRED = "SESSION_EXPIRED",
  SESSION_CREATE_ERROR = "SESSION_CREATE_ERROR",
  SESSION_UPDATE_ERROR = "SESSION_UPDATE_ERROR",
  INVALID_CREDENTIALS = "INVALID_CREDENTIALS",
  USER_NOT_VERIFIED = "USER_NOT_VERIFIED",
  USER_NOT_LOGGED_IN = "USER_NOT_LOGGED_IN",
}

export { AuthErrorCode };
