enum TokenErrorCodes {
  TOKEN_NOT_FOUND = "TOKEN_NOT_FOUND",
  TOKEN_ALREADY_USED = "TOKEN_ALREADY_USED",
  TOKEN_EXPIRED = "TOKEN_EXPIRED",
  TOKEN_NOT_BELONG_TO_USER = "TOKEN_NOT_BELONG_TO_USER"
}

export { TokenErrorCodes };
